/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import Clases.*;
import javax.swing.*;
import java.awt.*;
import java.net.URL;
/**
 *
 * @author Paul
 */
public class LogIn extends javax.swing.JFrame {

    /**
     * Creates new form LogIn
     */
    public LogIn() {
        initComponents();
        this.setLocationRelativeTo(this);
        
        SetImageLabel(Fondo, "/Imagenes/Fondo.png");
        SetImageLabel(LogoESPOCH, "/Imagenes/Logo ESPOCH.png");
        SetImageLabel(Titulo, "/Imagenes/Titulo.png");
        SetImageLabel(Pelotero, "/Imagenes/Pelotero.png");
        SetImageLabel(Text1, "/Imagenes/CuadroParaTexto.png");
        SetImageLabel(Text2, "/Imagenes/CuadroParaTexto.png");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pelotero = new javax.swing.JLabel();
        LogoESPOCH = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        txtpass = new javax.swing.JPasswordField();
        Text1 = new javax.swing.JLabel();
        Text2 = new javax.swing.JLabel();
        Log = new javax.swing.JLabel();
        In = new javax.swing.JLabel();
        Usuario1 = new javax.swing.JLabel();
        Usuario2 = new javax.swing.JLabel();
        Contraseña1 = new javax.swing.JLabel();
        Contraseña2 = new javax.swing.JLabel();
        SingUp = new javax.swing.JButton();
        LogIn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Pelotero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Pelotero.png"))); // NOI18N
        getContentPane().add(Pelotero, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 170, 350));

        LogoESPOCH.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogoESPOCH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo ESPOCH.png"))); // NOI18N
        getContentPane().add(LogoESPOCH, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 430, 200, 60));

        Titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Titulo.png"))); // NOI18N
        Titulo.setText("jLabel3");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 430, 60));

        txtuser.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        txtuser.setForeground(new java.awt.Color(204, 204, 204));
        txtuser.setText("Ingrese su usuario");
        txtuser.setBorder(null);
        txtuser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtuserFocusGained(evt);
            }
        });
        txtuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtuserMousePressed(evt);
            }
        });
        txtuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuserActionPerformed(evt);
            }
        });
        getContentPane().add(txtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 310, 20));

        txtpass.setFont(new java.awt.Font("Bebas Neue", 0, 15)); // NOI18N
        txtpass.setForeground(new java.awt.Color(204, 204, 204));
        txtpass.setText("***************");
        txtpass.setBorder(null);
        txtpass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpassFocusGained(evt);
            }
        });
        txtpass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtpassMousePressed(evt);
            }
        });
        txtpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpassActionPerformed(evt);
            }
        });
        getContentPane().add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 310, 20));

        Text1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CuadroParaTexto.png"))); // NOI18N
        getContentPane().add(Text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 340, 40));

        Text2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CuadroParaTexto.png"))); // NOI18N
        Text2.setText("jLabel2");
        getContentPane().add(Text2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 340, 40));

        Log.setFont(new java.awt.Font("Bebas Neue", 1, 55)); // NOI18N
        Log.setForeground(new java.awt.Color(255, 255, 255));
        Log.setText("Acceso");
        getContentPane().add(Log, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 230, 50));

        In.setFont(new java.awt.Font("Bebas Neue", 1, 55)); // NOI18N
        In.setText("Acceso");
        getContentPane().add(In, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 230, 60));

        Usuario1.setFont(new java.awt.Font("Bebas Neue", 1, 30)); // NOI18N
        Usuario1.setForeground(new java.awt.Color(255, 255, 255));
        Usuario1.setText("Usuario:");
        getContentPane().add(Usuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 290, 70));

        Usuario2.setFont(new java.awt.Font("Bebas Neue", 1, 30)); // NOI18N
        Usuario2.setText(" Usuario:");
        getContentPane().add(Usuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 310, 50));

        Contraseña1.setFont(new java.awt.Font("Bebas Neue", 1, 30)); // NOI18N
        Contraseña1.setForeground(new java.awt.Color(255, 255, 255));
        Contraseña1.setText("Contraseña:");
        getContentPane().add(Contraseña1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 310, 70));

        Contraseña2.setFont(new java.awt.Font("Bebas Neue", 1, 30)); // NOI18N
        Contraseña2.setText(" Contraseña:");
        getContentPane().add(Contraseña2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 330, 50));

        SingUp.setBackground(new java.awt.Color(188, 6, 19));
        SingUp.setFont(new java.awt.Font("Bebas Neue", 0, 20)); // NOI18N
        SingUp.setText("Registrate");
        SingUp.setActionCommand("Regístrate");
        SingUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SingUpActionPerformed(evt);
            }
        });
        getContentPane().add(SingUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, 120, 40));

        LogIn.setBackground(new java.awt.Color(188, 6, 19));
        LogIn.setFont(new java.awt.Font("Bebas Neue", 0, 20)); // NOI18N
        LogIn.setText("Iniciar Sesión");
        LogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogInActionPerformed(evt);
            }
        });
        getContentPane().add(LogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 120, 40));

        jLabel1.setFont(new java.awt.Font("Bebas Neue", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("¿No tienes una cuenta?");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 420, 210, -1));

        Fondo.setBackground(new java.awt.Color(153, 4, 17));
        Fondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.png"))); // NOI18N
        Fondo.setMaximumSize(new java.awt.Dimension(800, 500));
        Fondo.setMinimumSize(new java.awt.Dimension(800, 500));
        Fondo.setPreferredSize(new java.awt.Dimension(800, 500));
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 170, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtuserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtuserMousePressed
        if (txtuser.getText().equals("Ingrese su usuario")){
            txtuser.setText("");
            txtuser.setForeground(Color.black);
        }
        if (String.valueOf(txtpass.getPassword()).isEmpty()){
            txtpass.setText("***************");
            txtpass.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtuserMousePressed

    private void txtuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuserActionPerformed

    private void txtpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpassActionPerformed

    private void txtpassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtpassMousePressed
        if (String.valueOf(txtpass.getPassword()).equals("***************")){
            txtpass.setText("");
            txtpass.setForeground(Color.black);
        }
        if (txtuser.getText().isEmpty()){
            txtuser.setText("Ingrese su usuario");
            txtuser.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtpassMousePressed

    private void SingUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SingUpActionPerformed
        Registrarse RegistroFrame = new Registrarse();
        RegistroFrame.setVisible(true);
        RegistroFrame.pack();
        RegistroFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_SingUpActionPerformed

    private void LogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInActionPerformed
        Consultas con = new Consultas();
        MenuPrincipal Mainmenu = new MenuPrincipal();
        /*con.Acceso(txtuser.getText(), String.valueOf(txtpass.getText()));*/
        if (con.Acceso(txtuser.getText(), String.valueOf(txtpass.getText()))){
        Mainmenu.setVisible(true);
        Mainmenu.pack();
        Mainmenu.setLocationRelativeTo(null);
        this.dispose();
        }
        
        
        
    }//GEN-LAST:event_LogInActionPerformed

    private void txtuserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtuserFocusGained
        if (txtuser.getText().equals("Ingrese su usuario")){
            txtuser.setText("");
            txtuser.setForeground(Color.black);
        }
        if (String.valueOf(txtpass.getPassword()).isEmpty()){
            txtpass.setText("***************");
            txtpass.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtuserFocusGained

    private void txtpassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpassFocusGained
        if (String.valueOf(txtpass.getPassword()).equals("***************")){
            txtpass.setText("");
            txtpass.setForeground(Color.black);
        }
        if (txtuser.getText().isEmpty()){
            txtuser.setText("Ingrese su usuario");
            txtuser.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtpassFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
        
    
    }
    
    private void SetImageLabel(JLabel labelname, String resourcePath)
    {
        URL imageUrl = getClass().getResource(resourcePath);
        if (imageUrl != null) {
            ImageIcon image = new ImageIcon(imageUrl);
            Icon icon = new ImageIcon(image.getImage().getScaledInstance(labelname.getWidth(), labelname.getHeight(), Image.SCALE_DEFAULT));
            labelname.setIcon(icon);
            this.repaint();
        } else {
            System.out.println("Imagen no encontrada: " + resourcePath);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Contraseña1;
    private javax.swing.JLabel Contraseña2;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel In;
    private javax.swing.JLabel Log;
    private javax.swing.JButton LogIn;
    private javax.swing.JLabel LogoESPOCH;
    private javax.swing.JLabel Pelotero;
    private javax.swing.JButton SingUp;
    private javax.swing.JLabel Text1;
    private javax.swing.JLabel Text2;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel Usuario1;
    private javax.swing.JLabel Usuario2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
