/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import Clases.*;
import java.awt.*;
import java.net.URL;
import javax.swing.*;

/**
 *
 * @author Paul
 */
public class Registrarse extends javax.swing.JFrame {

    /**
     * Creates new form Registrarse
     */
    public Registrarse() {
        initComponents();
        this.setLocationRelativeTo(this);
        
        SetImageLabel(Fondinho,"/Imagenes/Fondo.png");
        SetImageLabel(LogoESPOCH,"/Imagenes/Logo ESPOCH.png");
        SetImageLabel(Pelotero,"/Imagenes/Pelotero.png");
        SetImageLabel(Text1,"/Imagenes/CuadroParaTexto.png");
        SetImageLabel(Text2,"/Imagenes/CuadroParaTexto.png");
        SetImageLabel(Text3,"/Imagenes/CuadroParaTexto.png");
        SetImageLabel(back,"/Imagenes/Back.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Registro1 = new javax.swing.JLabel();
        Registro2 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtuser = new javax.swing.JTextField();
        txtpass = new javax.swing.JPasswordField();
        Name1 = new javax.swing.JLabel();
        Name2 = new javax.swing.JLabel();
        Text1 = new javax.swing.JLabel();
        LogoESPOCH = new javax.swing.JLabel();
        Pelotero = new javax.swing.JLabel();
        Usuario1 = new javax.swing.JLabel();
        Usuario2 = new javax.swing.JLabel();
        Text2 = new javax.swing.JLabel();
        Pass1 = new javax.swing.JLabel();
        Pass2 = new javax.swing.JLabel();
        Text3 = new javax.swing.JLabel();
        PVolver = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        Volver = new javax.swing.JButton();
        Guardar = new javax.swing.JButton();
        Fondinho = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Registro1.setFont(new java.awt.Font("Bebas Neue", 1, 55)); // NOI18N
        Registro1.setForeground(new java.awt.Color(255, 255, 255));
        Registro1.setText("Registro");
        getContentPane().add(Registro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 330, 50));

        Registro2.setFont(new java.awt.Font("Bebas Neue", 1, 55)); // NOI18N
        Registro2.setText("Registro");
        getContentPane().add(Registro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 330, 60));

        txtname.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        txtname.setForeground(new java.awt.Color(204, 204, 204));
        txtname.setText("Ingrese su nombre");
        txtname.setBorder(null);
        txtname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtnameFocusGained(evt);
            }
        });
        txtname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtnameMousePressed(evt);
            }
        });
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        getContentPane().add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 310, 20));

        txtuser.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        txtuser.setForeground(new java.awt.Color(204, 204, 204));
        txtuser.setText("Ingrese su usuario");
        txtuser.setBorder(null);
        txtuser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtuserFocusGained(evt);
            }
        });
        txtuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtuserMousePressed(evt);
            }
        });
        txtuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuserActionPerformed(evt);
            }
        });
        getContentPane().add(txtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 310, 20));

        txtpass.setFont(new java.awt.Font("Bebas Neue", 0, 15)); // NOI18N
        txtpass.setForeground(new java.awt.Color(204, 204, 204));
        txtpass.setText("***************");
        txtpass.setBorder(null);
        txtpass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpassFocusGained(evt);
            }
        });
        txtpass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtpassMousePressed(evt);
            }
        });
        getContentPane().add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 310, 20));

        Name1.setFont(new java.awt.Font("Bebas Neue", 1, 30)); // NOI18N
        Name1.setForeground(new java.awt.Color(255, 255, 255));
        Name1.setText("Nombre:");
        getContentPane().add(Name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 300, 70));

        Name2.setFont(new java.awt.Font("Bebas Neue", 1, 30)); // NOI18N
        Name2.setText(" Nombre:");
        getContentPane().add(Name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 320, 50));

        Text1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CuadroParaTexto.png"))); // NOI18N
        getContentPane().add(Text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 340, 40));

        LogoESPOCH.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogoESPOCH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo ESPOCH.png"))); // NOI18N
        getContentPane().add(LogoESPOCH, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 430, 200, 60));

        Pelotero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Pelotero.png"))); // NOI18N
        getContentPane().add(Pelotero, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 170, 350));

        Usuario1.setFont(new java.awt.Font("Bebas Neue", 1, 30)); // NOI18N
        Usuario1.setForeground(new java.awt.Color(255, 255, 255));
        Usuario1.setText("Usuario:");
        getContentPane().add(Usuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 230, 70));

        Usuario2.setFont(new java.awt.Font("Bebas Neue", 1, 30)); // NOI18N
        Usuario2.setText(" Usuario:");
        getContentPane().add(Usuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 250, 50));

        Text2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CuadroParaTexto.png"))); // NOI18N
        getContentPane().add(Text2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 340, 40));

        Pass1.setFont(new java.awt.Font("Bebas Neue", 1, 30)); // NOI18N
        Pass1.setForeground(new java.awt.Color(255, 255, 255));
        Pass1.setText("Contraseña:");
        getContentPane().add(Pass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 270, 70));

        Pass2.setFont(new java.awt.Font("Bebas Neue", 1, 30)); // NOI18N
        Pass2.setText(" Contraseña:");
        getContentPane().add(Pass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 290, 50));

        Text3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CuadroParaTexto.png"))); // NOI18N
        getContentPane().add(Text3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 340, 40));

        PVolver.setFont(new java.awt.Font("Bebas Neue", 0, 20)); // NOI18N
        PVolver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PVolver.setText("Volver");
        getContentPane().add(PVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 80, 30));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Back.png"))); // NOI18N
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 40, 40));

        Volver.setBackground(new java.awt.Color(188, 6, 19));
        Volver.setFont(new java.awt.Font("Bebas Neue", 0, 20)); // NOI18N
        Volver.setForeground(new java.awt.Color(255, 255, 255));
        Volver.setToolTipText("");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });
        getContentPane().add(Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 60));

        Guardar.setBackground(new java.awt.Color(188, 6, 19));
        Guardar.setFont(new java.awt.Font("Bebas Neue", 0, 20)); // NOI18N
        Guardar.setText("Registrarse");
        Guardar.setPreferredSize(new java.awt.Dimension(120, 31));
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });
        getContentPane().add(Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, 140, 40));

        Fondinho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo.png"))); // NOI18N
        Fondinho.setText("Volver");
        Fondinho.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Fondinho.setPreferredSize(new java.awt.Dimension(800, 500));
        getContentPane().add(Fondinho, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        if (!txtname.getText().equals("Ingrese su nombre") && !txtuser.getText().equals("Ingrese su usuario") && !String.valueOf(txtpass.getText()).equals("***************")){
        Consultas con = new Consultas();
        con.GuardarUsuario(txtname.getText(), txtuser.getText(), String.valueOf(txtpass.getText()));
        LogIn loginFrame = new LogIn();
        loginFrame.setVisible(true);
        loginFrame.pack();
        loginFrame.setLocationRelativeTo(null);
        this.dispose();
        }
        else 
        {
            JOptionPane.showMessageDialog(null, "Complete toda la información");
        }
    }//GEN-LAST:event_GuardarActionPerformed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void txtnameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnameMousePressed
        if (txtname.getText().equals("Ingrese su nombre")){
            txtname.setText("");
            txtname.setForeground(Color.black);
        }
        if (String.valueOf(txtpass.getText()).isEmpty()){
            txtpass.setText("***************");
            txtpass.setForeground(Color.gray);
        }
        if(txtuser.getText().isEmpty()){
            txtuser.setText("Ingrese su usuario");
            txtuser.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtnameMousePressed

    private void txtuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuserActionPerformed

    private void txtuserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtuserMousePressed
        if (txtuser.getText().equals("Ingrese su usuario")){
            txtuser.setText("");
            txtuser.setForeground(Color.black);
        }
        if (String.valueOf(txtpass.getText()).isEmpty()){
            txtpass.setText("***************");
            txtpass.setForeground(Color.gray);
            
        }
        if (txtname.getText().isEmpty()){
            txtname.setText("Ingrese su nombre");
            txtname.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtuserMousePressed

    private void txtpassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtpassMousePressed
        if (String.valueOf(txtpass.getText()).equals("***************")){
            txtpass.setText("");
            txtpass.setForeground(Color.black);
        }
        if (txtuser.getText().isEmpty()){
            txtuser.setText("Ingrese su usuario");
            txtuser.setForeground(Color.gray);
        }
        if (txtname.getText().isEmpty()){
            txtname.setText("Ingrese su nombre");
            txtname.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtpassMousePressed

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        LogIn loginFrame = new LogIn();
        loginFrame.setVisible(true);
        loginFrame.pack();
        loginFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_VolverActionPerformed

    private void txtnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnameFocusGained
        if (txtname.getText().equals("Ingrese su nombre")){
            txtname.setText("");
            txtname.setForeground(Color.black);
        }
        if (String.valueOf(txtpass.getText()).isEmpty()){
            txtpass.setText("***************");
            txtpass.setForeground(Color.gray);
        }
        if(txtuser.getText().isEmpty()){
            txtuser.setText("Ingrese su usuario");
            txtuser.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtnameFocusGained

    private void txtuserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtuserFocusGained
        if (txtuser.getText().equals("Ingrese su usuario")){
            txtuser.setText("");
            txtuser.setForeground(Color.black);
        }
        if (String.valueOf(txtpass.getText()).isEmpty()){
            txtpass.setText("***************");
            txtpass.setForeground(Color.gray);
            
        }
        if (txtname.getText().isEmpty()){
            txtname.setText("Ingrese su nombre");
            txtname.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtuserFocusGained

    private void txtpassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpassFocusGained
        if (String.valueOf(txtpass.getText()).equals("***************")){
            txtpass.setText("");
            txtpass.setForeground(Color.black);
        }
        if (txtuser.getText().isEmpty()){
            txtuser.setText("Ingrese su usuario");
            txtuser.setForeground(Color.gray);
        }
        if (txtname.getText().isEmpty()){
            txtname.setText("Ingrese su nombre");
            txtname.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txtpassFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrarse().setVisible(true);
            }
        });
    }
    
    private void SetImageLabel(JLabel labelname, String resourcePath)
    {
        URL imageUrl = getClass().getResource(resourcePath);
        if (imageUrl != null) {
            ImageIcon image = new ImageIcon(imageUrl);
            Icon icon = new ImageIcon(image.getImage().getScaledInstance(labelname.getWidth(), labelname.getHeight(), Image.SCALE_DEFAULT));
            labelname.setIcon(icon);
            this.repaint();
        } else {
            System.out.println("Imagen no encontrada: " + resourcePath);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondinho;
    private javax.swing.JButton Guardar;
    private javax.swing.JLabel LogoESPOCH;
    private javax.swing.JLabel Name1;
    private javax.swing.JLabel Name2;
    private javax.swing.JLabel PVolver;
    private javax.swing.JLabel Pass1;
    private javax.swing.JLabel Pass2;
    private javax.swing.JLabel Pelotero;
    private javax.swing.JLabel Registro1;
    private javax.swing.JLabel Registro2;
    private javax.swing.JLabel Text1;
    private javax.swing.JLabel Text2;
    private javax.swing.JLabel Text3;
    private javax.swing.JLabel Usuario1;
    private javax.swing.JLabel Usuario2;
    private javax.swing.JButton Volver;
    private javax.swing.JLabel back;
    private javax.swing.JTextField txtname;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
